description: "Building Automation LLM Evaluation: Fine-tuned vs. Baseline"

providers:
  - id: "python:custom_provider.py:call_agent"
    config:
      model_type: "finetuned"
      description: "Fine-tuned model running on local PEFT server"
    
  - id: "python:custom_provider.py:call_agent"
    config:
      model_type: "baseline"
      description: "Baseline qwen3:4b-q8_0 model from Ollama"

prompts:
  - "{{query}}"

tests: file://building_test_cases.yaml

defaultTest:
  assert:
    - type: javascript
      value: file://assertions/tool_accuracy.js
    
    - type: javascript  
      value: file://assertions/domain_knowledge.js
    
    - type: javascript
      value: file://assertions/safety_compliance.js
    
    - type: javascript
      value: file://assertions/performance_metrics.js

outputPath: ./results/evaluation_results.json
sharing: false

evaluateOptions:
  maxConcurrency: 1